sudo: required
before_install:
  - sudo apt-get install libao-dev
  - sudo apt-get install libcurl4-openssl-dev

  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  - clang
  

# Build steps
script:
  - mkdir build
  - cd build
  - cmake ..